version: '3'

services:
    build-gp2040-ce:
        build: .
        env_file: build.env # this file is ignored by git -- only using it for push notifications (see build.sh)
        volumes:
            - ./:/usr/src/app/
        tty: true
        